<a href="https://colab.research.google.com/github/arenasdelgadopaula-star/credit-risk-analysis/blob/main/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("loans.db")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!cp loans.db "/content/drive/MyDrive/loan_data/loans.db"

In [4]:
conn = sqlite3.connect("loans.db")
pd.read_sql_query("SELECT COUNT(*) AS n FROM loans;", conn)

         n
0  2260668

In [5]:
pd.read_sql_query("SELECT SUBSTR(issue_d, -4) AS year, COUNT(*) AS loans FROM loans GROUP BY year ORDER BY year;", conn)

    year   loans
0   2007     603
1   2008    2393
2   2009    5281
3   2010   12537
4   2011   21721
5   2012   53367
6   2013  134814
7   2014  235629
8   2015  421095
9   2016  434407
10  2017  443579
11  2018  495242

In [6]:
pd.read_sql_query("SELECT loan_status, COUNT(*) AS loans FROM loans GROUP BY loan_status ORDER BY loans DESC;", conn)

                                         loan_status    loans
0                                         Fully Paid  1041952
1                                            Current   919695
2                                        Charged Off   261655
3                                 Late (31-120 days)    21897
4                                    In Grace Period     8952
5                                  Late (16-30 days)     3737
6  Does not meet the credit policy. Status:Fully ...     1988
7  Does not meet the credit policy. Status:Charge...      761
8                                            Default       31